services:
  api-server:
    build: 
      context: .
      dockerfile: ./Dockerfile.api
    ports:
      - 8000:8000
    container_name: 'api-server'
  # model-runner:
  #   build: Dockerfile.model-runner
  #   container_name: 'model-runner'
  web:
    build: 
      context: .
      dockerfile: ./Dockerfile.web
    ports:
      - 8001:80
    container_name: 'web'
  rabbitmq:
    image: rabbitmq:3.11-management
    container_name: 'rabbitmq'
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
      - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq