services:
  api-server:
    container_name: 'api-server'
    build: 
      context: .
      dockerfile: ./Dockerfile.api
    ports:
      - 8000:8000
    env_file:
      - /home/shared/.env
    command: ["runserver_plus", "--cert-file", "acom.ucar.edu.crt", "--key-file", "acom.ucar.edu.key", "0.0.0.0:8000"]
    volumes:
      - db-data:/music-box-interactive/interactive
      - /etc/pki/:/music-box-interactive
    network_mode: "host"
    restart: on-failure
    logging:
      driver: "json-file"
      options:
        max-size: "10m"    # Maximum size of each log file, e.g., 10 megabytes
        max-file: "5"      # Maximum number of log files to retain
  model-runner:
    build: 
      context: .
      dockerfile: ./Dockerfile.model_runner
    env_file:
      - /home/shared/.env
    restart: on-failure
    deploy:
      mode: replicated
      replicas: 3
    network_mode: "host"
    logging:
      driver: "json-file"
      options:
        max-size: "10m"    # Maximum size of each log file, e.g., 10 megabytes
        max-file: "5"      # Maximum number of log files to retain
  status-listener:
    container_name: 'status-listener'
    build: 
      context: .
      dockerfile: ./Dockerfile.status_listener
    env_file:
      - /home/shared/.env
    volumes:
      - db-data:/music-box-interactive/interactive
    restart: on-failure
    network_mode: "host"
    logging:
      driver: "json-file"
      options:
        max-size: "10m"    # Maximum size of each log file, e.g., 10 megabytes
        max-file: "5"      # Maximum number of log files to retain
volumes:
  db-data: