services:
  api-server:
    container_name: 'api-server'
    build: 
      context: .
      dockerfile: ./docker/Dockerfile.api
      args:
        - INSTALL_PyPartMC=true
    ports:
      - 8000:8000
    env_file:
      - ./.env
    volumes:
      - db-data:/music-box-interactive/interactive
      - partmc-data:/music-box-interactive/interactive/partmc-volume
  model-runner:
    container_name: 'model-runner'
    build: 
      context: .
      dockerfile: ./docker/Dockerfile.model_runner
      args:
        - INSTALL_PyPartMC=true
    env_file:
      - ./.env
    depends_on:
      - rabbitmq
    restart: on-failure
    deploy:
      mode: replicated
      replicas: 1
    volumes:
      - partmc-data:/partmc/partmc-volume
  status-listener:
    container_name: 'status-listener'
    build: 
      context: .
      dockerfile: ./docker/Dockerfile.status_listener
    env_file:
      - ./.env
    volumes:
      - db-data:/music-box-interactive/interactive
    depends_on:
      - rabbitmq
    restart: on-failure
  rabbitmq:
    container_name: 'rabbitmq'
    image: rabbitmq:3.11-management
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
      - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 5s
      timeout: 15s
      retries: 1
volumes:
  db-data:
  partmc-data: