services:
  api-server:
    container_name: 'api-server'
    build: 
      context: .
      dockerfile: ./Dockerfile.api-prod
    env_file:
      - /usr/share/music-box/.env
    volumes:
      - db-data:/music-box-interactive/interactive
      -  /etc/pki/:/music-box-interactive
  model-runner:
    build: 
      context: .
      dockerfile: ./Dockerfile.model_runner
    env_file:
      - /usr/share/music-box/.env
    restart: on-failure
    deploy:
      mode: replicated
      replicas: 3
  status-listener:
    container_name: 'status-listener'
    build: 
      context: .
      dockerfile: ./Dockerfile.status_listener
    env_file:
      - /usr/share/music-box/.env
    volumes:
      - db-data:/music-box-interactive/interactive
    restart: on-failure
volumes:
  db-data:
