services:
  api-server:
    build: 
      context: .
      dockerfile: ./Dockerfile.api
    ports:
      - 8000:8000
    container_name: 'api-server'
  model-runner:
    build: 
      context: .
      dockerfile: ./Dockerfile.model_runner
    depends_on:
      - rabbitmq
    restart: on-failure
    deploy:
      mode: replicated
      replicas: 3
  web:
    build: 
      context: .
      dockerfile: ./Dockerfile.web
    ports:
      - 8001:80
    container_name: 'web'
  rabbitmq:
    image: rabbitmq:3.11-management
    container_name: 'rabbitmq'
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
      - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 5s
      timeout: 15s
      retries: 1