services:
  api-server:
    build: 
      context: .
      dockerfile: ./Dockerfile.api
    ports:
      - 8000:8000
    container_name: 'api-server'
  model-runner:
    build: 
      context: .
      dockerfile: ./Dockerfile.model_runner
    depends_on:
      - rabbitmq
    command: sh -c '/wait-for-it/wait-for-it.sh rabbitmq:5672 --timeout=30 -- node consumer.js'
    container_name: 'model-runner'
    networks:
        - rabbitmq-network
  web:
    build: 
      context: .
      dockerfile: ./Dockerfile.web
    ports:
      - 8001:80
    container_name: 'web'
  rabbitmq:
    image: rabbitmq:3.11-management
    container_name: 'rabbitmq'
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
      - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
    networks:
        - rabbitmq-network
networks:
  rabbitmq-network:
    driver: bridge