name: Django CI with Docker Compose

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
  
jobs:
  test-backend:
    runs-on: ubuntu-latest

    services:
      docker:
        image: docker:19.03.12
        options: --privileged

    steps:
    
      - uses: actions/checkout@v2

      - name: Run docker-compose
        uses: hoverkraft-tech/compose-action@v2.0.1
        with:
          compose-file: "./docker-compose.yml"
      
      - name: Run migrations
        working-directory: ./backend
        run: |
          docker exec api-server bash -c "
          cd interactive &&
          poetry run python manage.py makemigrations &&
          poetry run python manage.py migrate"


      - name: Run pytest
        working-directory: ./backend
        run: |
          docker compose exec -T api-server sh -c "poetry run pytest"

      - name: Shut down Docker Compose
        if: always()
        working-directory: ./backend
        run: |
          docker compose down
