apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

images:
- name: hub.k8s.ucar.edu/musicbox/frontend
  newTag: 9edc9fc

resources:
- frontend-deploy.yaml
- frontend-service.yaml
- ingress.yaml

labels:
- includeSelectors: true
  pairs:
    app.kubernetes.io/instance: prod
    app.kubernetes.io/name: musicbox
